apiVersion: v1
kind: Service
metadata:
  name: lab4-backend-svc
  namespace: lab4
spec:
  selector:
    name: lab4-backend
  type: NodePort # Expose the service on a cluster-internal IP
  ports: # List of ports to expose
    - protocol: TCP
      port: 5050 # Port to expose on the service
      targetPort: 5050 # Port the service will forward to
      nodePort: 30200 # Port to access the service from outside the cluster