apiVersion: v1
kind: Service
metadata:
  name: lab4-mongodb-svc
  namespace: lab4
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP