apiVersion: v1
kind: Service
metadata:
  name: lab4-frontend-svc
  namespace: lab4
spec:
  selector:
    app: lab4-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
  type: NodePort